version: '3'

services:
    wordpress:
        image: wordpress
        container_name: wordpress
        restart: always
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_NAME: wordpressdb
            WORDPRESS_DB_USER: anas
            WORDPRESS_DB_PASSWORD: benani
        ports:
            - 8080:80
            - 443:443
    db:
        image: mysql
        container_name: mysql
        restart: always
        command: "--default-authentication-plugin=mysql_native_password"
        environment:
            MYSQL_ROOT_PASSWORD: benani
            MYSQL_DATABASE: wordpressdb
            MYSQL_USER: anas
            MYSQL_PASSWORD: benani
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8081:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORT: benani

